/**
 * Extensible fine-tuning model type configuration.
 * Add new entries here to support additional model types.
 * Each category maps 1-to-1 with a folder in the finetuner clips-dir.
 * The 'none' class is auto-generated by the backend — do NOT list it here.
 */
export const TUNING_MODEL_CONFIGS = [
  {
    id: 'event_detector',
    label: 'Event Detector',
    annotationType: 'point',
    categories: [
      { id: 'start',  label: 'START',  color: '#22d3ee', key: '1' },
      { id: 'end',    label: 'END',    color: '#f43f5e', key: '2' },
      { id: 'choice', label: 'CHOICE', color: '#f59e0b', key: '3' },
    ],
    minClips: 6,
  },
  {
    id: 'boss_detector',
    label: 'Boss Detector',
    annotationType: 'segment',
    categories: [
      { id: 'boss', label: 'BOSS FIGHT', color: '#f97316', key: '1' },
    ],
    minSegments: 5,
    minSegmentDuration: 3.0,
  },
];

export const TUNING_MODEL_CONFIG_BY_ID = Object.fromEntries(
  TUNING_MODEL_CONFIGS.map((c) => [c.id, c]),
);

/** Convert absolute file path to gamelens-local:// URL for video element src */
export function toLocalUrl(filePath) {
  if (!filePath) return '';
  const normalized = filePath.replace(/\\/g, '/');
  const withSlash = normalized.startsWith('/') ? normalized : '/' + normalized;
  const encoded = withSlash.split('/').map(encodeURIComponent).join('/');
  return `gamelens-local://${encoded}`;
}
