from __future__ import annotations

from typing import Protocol

from .models import DashboardStats, GameInfo, RunDetails, RunSummary, VersionInfo


class GameRepo(Protocol):
    def list_games(self) -> list[GameInfo]: ...
    def ensure_game(self, game_name: str) -> GameInfo: ...
    def list_versions(self, game: GameInfo) -> list[VersionInfo]: ...
    def ensure_version(self, game: GameInfo, version_name: str) -> VersionInfo: ...


class AnalyticsReader(Protocol):
    def load_dashboard_stats(self, version: VersionInfo) -> DashboardStats: ...
    def load_run_summaries(self, version: VersionInfo) -> list[RunSummary]: ...
    def load_run_details(self, version: VersionInfo, run_summary: RunSummary) -> RunDetails: ...


class JsonLoader(Protocol):
    def load(self, path: object) -> dict | list: ...
